### PR TITLE
Using Polymer generic directive

### PR DESCRIPTION
**Pull request by manolo**
Connects to vaadin/components-team-tasks#132

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-ng2-demo/8)

### CODE REVIEW

**Comment by tomivirkki** [comment]
This patch should remove the old PolymerElement directive (app/polymer-element) used (at least) in the expense editor.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/expense-manager-ng2-demo/8#-:-KGqneypyaZiglbtxZM4:-1871915908)*

**Comment by tomivirkki** [comment]
The branch doesn't work (with newest Angular) and can't be merged to master either. Needs to be rebased.

**Comment by Saulis** [comment]
Rebased

**Comment by tomivirkki** [comment]
I think you missed the last patch by Manolo from the branch during rebase (it removed the old polymer-element directive)

**Comment by Saulis** [comment]
Right, I pushed a rebased version I did yesterday. @manolo can you apply your patch again or push it in another branch so I can cherry-pick it?

**Comment by tomivirkki** [comment]
*[app/expenses-list/expenses_list.component.html, line 6 \[r6\]](https://reviewable.io:443/reviews/vaadin/expense-manager-ng2-demo/8#-KHTVQr9Hna3J4V7wzNq:-KHTVQr9Hna3J4V7wzNr:-334043545) ([raw file](https://github.com/vaadin/expense-manager-ng2-demo/blob/c3495a2c0f2b3c60aa4235ee526f8610c0ad3163/app/expenses-list/expenses_list.component.html#L6)):*
> ```HTML
>     <colgroup>
>       <col name="date" width="120" sortable sort-direction="desc"/>
>       <col name="merchant" sortable hidable />
> ```

These were intentionally removed earlier. Please revert these. The additional png image should be removed also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/expense-manager-ng2-demo/8)*

**Comment by tomivirkki** [comment]
*[package.json, line 26 \[r6\]](https://reviewable.io:443/reviews/vaadin/expense-manager-ng2-demo/8#-KHTbDaHnBWCF-xZjbMj:-KHTbDaHnBWCF-xZjbMk:-372580512) ([raw file](https://github.com/vaadin/expense-manager-ng2-demo/blob/c3495a2c0f2b3c60aa4235ee526f8610c0ad3163/package.json#L26)):*
> ```JSON
>     "systemjs": "0.19.27",
>     "zone.js": "0.6.12",
>     "vaadin-ng2-polymer": "vaadin/vaadin-ng2-polymer#fix/function_binding"
> ```

Do not depend on a feature/fix branch! This can't be merged to master as fix/function_binding will be removed as soon as it's merged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/expense-manager-ng2-demo/8)*

**Comment by manolo** [comment]
Rebased everything, Should work now, 

<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Right, I pushed a rebased version I did yesterday. @manolo can you apply your patch again or push it in another branch so I can cherry-pick it?</details>


---

Review status: 0 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[package.json, line 26 \[r6\]](https://reviewable.io:443/reviews/vaadin/expense-manager-ng2-demo/8#-KHTbDaHnBWCF-xZjbMj:-KHUqVuaX2u805J7-Nzl:-499146009) ([raw file](https://github.com/vaadin/expense-manager-ng2-demo/blob/c3495a2c0f2b3c60aa4235ee526f8610c0ad3163/package.json#L26)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> Do not depend on a feature/fix branch! This can't be merged to master as fix/function_binding will be removed as soon as it's merged.</details>
Done.

---

*[app/expenses-list/expenses_list.component.html, line 6 \[r6\]](https://reviewable.io:443/reviews/vaadin/expense-manager-ng2-demo/8#-KHTVQr9Hna3J4V7wzNq:-KHUq_kpdRxh54ziuJI4:-1345413991) ([raw file](https://github.com/vaadin/expense-manager-ng2-demo/blob/c3495a2c0f2b3c60aa4235ee526f8610c0ad3163/app/expenses-list/expenses_list.component.html#L6)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> These were intentionally removed earlier. Please revert these. The additional png image should be removed also.</details>
Ok, I didn't saw any commit message or comment related with this, so I thought it was a mistake.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/expense-manager-ng2-demo/8#-:-KHQnB-zrbYyf7NT3D5j:-848498660)*

**Comment by tomivirkki** [comment]
:lgtm: except for the missing chart.

<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> Rebased everything, Should work now, </details>


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/expense-manager-ng2-demo/8#-:-KHV2Dr3eKh5Kch8ob3v:-34556376)*

**Comment by manolo** [comment]
Broken in : https://github.com/vaadin/vaadin-ng2-polymer/commit/6b654ce5c8a0652a461386853d1cb2109be435cf

<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> :lgtm: except for the missing chart.</details>


---

Review status: 0 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/expense-manager-ng2-demo/8#-:-KHVH2QDCAiU_TxhkUNG:1911650816)*

**Comment by manolo** [comment]
Actually is not broken, just a requirements in charts to set  certain properties the notify flag to true.
I guess is ok to merge this, and not deploy until charts fix is merged

<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> Broken in : https://github.com/vaadin/vaadin-ng2-polymer/commit/6b654ce5c8a0652a461386853d1cb2109be435cf</details>


---

Review status: 0 of 24 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/expense-manager-ng2-demo/8#-:-KHW7T9mctKMI1XXFJX1:-1239293430)*

**Comment by Saulis** [comment]
Chart gets fixed with https://github.com/vaadin/vaadin-charts/pull/121

Shall we wait or merge now and update deps later?

**Pull request merged**
