### PR TITLE
Update Angular 2 final version

### PR DESCRIPTION
**Pull request by samiheikki**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-ng2-demo/13)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Getting some errors in the console after running `npm start`

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/expense-manager-ng2-demo/13#-:-KS_Uea3SewOQORkgD2l:b-bcny7v)*

**Comment by samiheikki** [comment]
What kind of errors? @tomivirkki

**Comment by samiheikki** [comment]
I removed git ignore from typings folder. Can you try again? @tomivirkki

**Comment by tomivirkki** [comment]
Seems to be working now

---

Reviewed 48 of 49 files at r1, 12 of 12 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/expense-manager-ng2-demo/13#-:-KS_ekOtoG1Yf9UUfCY7:b-8otrj1)*

**Pull request merged**
